//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public string LaptopID { get; set; }
        public string Name { get; set; }
        public long price { get; set; }
        public string icon { get; set; }
        public string slide { get; set; }
        public string images { get; set; }
        public string CPU_Manf { get; set; }
        public string CPU_Tech { get; set; }
        public string CPU_Type { get; set; }
        public string CPU_Speed { get; set; }
        public string CPU_Cache { get; set; }
        public string CPU_MaxSpeed { get; set; }
        public string MainBoard_Chipset { get; set; }
        public string MainBoard_Bus { get; set; }
        public string MainBoard_SupporRam { get; set; }
        public string Storage_Type { get; set; }
        public string Storage_RAM { get; set; }
        public string Storage_Bus { get; set; }
        public string HardDisk_Type { get; set; }
        public string HardDisk_Capacity { get; set; }
        public string screenSize { get; set; }
        public string screenResolution { get; set; }
        public string screenTech { get; set; }
        public string touchScreen { get; set; }
        public string Graphics_Chipset { get; set; }
        public string Graphics_Capacity { get; set; }
        public string Graphics_Design { get; set; }
        public string Audio_Channels { get; set; }
        public string Audio_Other { get; set; }
        public string CD { get; set; }
        public string CD_Type { get; set; }
        public string Interfaces { get; set; }
        public string Interfaces_Other { get; set; }
        public string LAN { get; set; }
        public string Wifi { get; set; }
        public string Network_Other { get; set; }
        public string CardReader_Support { get; set; }
        public string CardReader_Other { get; set; }
        public string Webcam_Resolution { get; set; }
        public string Webcam_Other { get; set; }
        public string Battery { get; set; }
        public string OS { get; set; }
        public string dimensions { get; set; }
        public string weight { get; set; }
    }
}
