//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderID { get; set; }
        public string ProductsID { get; set; }
        public long Prices { get; set; }
        public int Quantity { get; set; }
        public Nullable<float> Discount { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
