//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablet
    {
        public string TabletID { get; set; }
        public string Name { get; set; }
        public string icon { get; set; }
        public string slide { get; set; }
        public string images { get; set; }
        public long price { get; set; }
        public string manuf { get; set; }
        public string descImg { get; set; }
        public string screenTech { get; set; }
        public string screenResolution { get; set; }
        public string screenSize { get; set; }
        public string touchScreen { get; set; }
        public string CameraBehind { get; set; }
        public string film { get; set; }
        public string Advanced { get; set; }
        public string CameraFront { get; set; }
        public string OS { get; set; }
        public string Chipset { get; set; }
        public string NumCore { get; set; }
        public string Speed { get; set; }
        public string GPU { get; set; }
        public string RAM { get; set; }
        public string ROM { get; set; }
        public string availability { get; set; }
        public string memoryCard { get; set; }
        public string MaximumSupport { get; set; }
        public string ThreeG { get; set; }
        public string FourG { get; set; }
        public string SIM { get; set; }
        public string Wifi { get; set; }
        public string GPS { get; set; }
        public string Bluetooth { get; set; }
        public string USB { get; set; }
        public string HDMI { get; set; }
        public string audioJack { get; set; }
        public string Connection_Other { get; set; }
        public string dimensions { get; set; }
        public string weight { get; set; }
        public string Capacity { get; set; }
        public string Battery_Type { get; set; }
    }
}
